### ISSUE TITLE
Errors on server and client

### ISSUE THREAD

**Issue by darkstar27** [gammarf/gammarf#55]
Server at https://kcgrf.gammarf.io states (only after login):
502 Bad Gateway

and client returns the following when checking for stations:
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f49680d5ba8>: Failed to establish a new connection: [Errno 113] No route to host',)': /util/locations
[2018-12-10 01:21:04] error getting station information from server

Are you having server side issues or did I mis-configure something?

Thanks

**Comment by gammarf** [comment]
Didn't see this, sorry.  The server was probably down then.  It should work fine now
